# Generated by Django 5.0 on 2023-12-05 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=20)),
                ("customer_last_name", models.CharField(max_length=20)),
                ("contact_information", models.JSONField()),
                ("time", models.DateTimeField()),
                (
                    "payer",
                    models.CharField(
                        choices=[
                            ("direct_client", "Direct Client"),
                            ("agency", "Agency"),
                        ],
                        max_length=15,
                    ),
                ),
                ("number_of_guests", models.IntegerField()),
                ("tour_type", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_information", models.JSONField()),
                ("travel_preferences", models.JSONField()),
                ("travel_history", models.TextField()),
                ("preferred_language", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_person_name", models.CharField(max_length=255)),
                ("contact_person_last_name", models.CharField(max_length=255)),
                ("email_address", models.EmailField(max_length=254)),
                ("contact_information", models.JSONField()),
                ("preferred_languages", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TourPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tour_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("itinerary", models.TextField()),
                ("duration", models.IntegerField()),
                ("included", models.TextField()),
                ("excluded", models.TextField()),
                ("remarks", models.TextField()),
                ("pricing", models.JSONField()),
                ("availability", models.JSONField()),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour_management.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourPackagePricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_tier", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("profit_margin_type", models.CharField(max_length=255)),
                (
                    "profit_margin_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour_management.season",
                    ),
                ),
                (
                    "tour_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour_management.tourpackage",
                    ),
                ),
            ],
        ),
    ]
