# Generated by Django 4.2.7 on 2023-12-07 01:19

from django.db import migrations


def populate_pricing(apps, schema_editor):
    Supplier = apps.get_model("tour_management", "Supplier")
    Pricing = apps.get_model("tour_management", "Pricing")

    # Assuming you want to set the default Pricing for existing suppliers
    default_pricing, created = Pricing.objects.get_or_create(
        agency_rate=0, direct_customer_rate=0, supplier_cost=0, profit_margin=0
    )

    Supplier.objects.filter(pricing=None).update(pricing=default_pricing)


class Migration(migrations.Migration):
    dependencies = [
        ("tour_management", "0001_initial"),
    ]

    operations = []
