# Generated by Django 4.2.7 on 2023-12-07 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tour_management", "0002_auto_20231207_0119"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("information", models.TextField()),
                ("special_request", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CommissionAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commission_rate", models.IntegerField()),
                ("payment_terms", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20, null=True)),
                ("last_name", models.CharField(max_length=20, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("sub_admin", "Sub Admin"),
                            ("agency", "Agency"),
                            ("supplier", "Supplier"),
                            ("representative", "Representative"),
                            ("customer", "Customer"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("contact_information", models.JSONField()),
                ("travel_preferences", models.JSONField()),
                ("travel_history", models.TextField()),
                ("prefered_language", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="GuideAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("preferred_language", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_content", models.TextField()),
                (
                    "payer",
                    models.CharField(
                        choices=[
                            ("direct_client", "Direct Client"),
                            ("agency", "Agency"),
                        ],
                        default="direct_client",
                        max_length=15,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="tour_management.customuser",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="tour_management.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnlineUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour_management.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.TextField()),
                ("status", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agency_rate", models.IntegerField(default=0)),
                ("direct_customer_rate", models.IntegerField(default=0)),
                ("supplier_cost", models.IntegerField(default=0)),
                ("profit_margin", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("booking", "Booking"),
                            ("sales", "Sales"),
                            ("customer_activity", "Customer Activity"),
                            ("supplier_performance", "Supplier Performance"),
                        ],
                        default="booking",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interface_language", models.TextField()),
                ("pickup_list", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour_management.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("shift_time", models.DateTimeField()),
                (
                    "shift_option",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("night", "Night"),
                        ],
                        default="morning",
                        max_length=15,
                    ),
                ),
                (
                    "tour_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour_management.tourpackage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "tour_type",
                    models.CharField(
                        choices=[
                            ("Aerial", "Aerial"),
                            ("Adventure", "Adventure"),
                            ("Aquatic", "Aquatic"),
                            ("Combined", "Combined"),
                            ("Extreme", "Extreme"),
                            ("Nightout", "Nightout"),
                            ("Sightseeing", "Sightseeing"),
                            ("Terrestrial", "Terrestrial"),
                        ],
                        default="Aerial",
                        max_length=15,
                    ),
                ),
                ("guide_assigned", models.TextField()),
                ("shift_details", models.TextField()),
                (
                    "payer",
                    models.CharField(
                        choices=[
                            ("direct_client", "Direct Client"),
                            ("agency", "Agency"),
                        ],
                        default="direct_client",
                        max_length=15,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour_management.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField()),
                ("history", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour_management.customuser",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="time",
            new_name="date_time",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="contact_information",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="contact_person_last_name",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="contact_person_name",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="email_address",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="name",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="preferred_languages",
        ),
        migrations.AlterField(
            model_name="booking",
            name="payer",
            field=models.CharField(
                choices=[("direct_client", "Direct Client"), ("agency", "Agency")],
                default="direct_client",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="tour_type",
            field=models.CharField(
                choices=[
                    ("Aerial", "Aerial"),
                    ("Adventure", "Adventure"),
                    ("Aquatic", "Aquatic"),
                    ("Combined", "Combined"),
                    ("Extreme", "Extreme"),
                    ("Nightout", "Nightout"),
                    ("Sightseeing", "Sightseeing"),
                    ("Terrestrial", "Terrestrial"),
                ],
                default="Aerial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tour_management.customuser",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="pricing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tour_management.pricing",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tour_management.customuser",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tour_management.customuser",
            ),
        ),
    ]
