# Generated by Django 4.2.7 on 2023-12-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour_management", "0003_client_commissionagreement_customuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="contact_information",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="travel_history",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="travel_preferences",
            field=models.JSONField(null=True),
        ),
    ]
