# Generated by Django 4.2.7 on 2023-12-07 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tour_management", "0004_alter_customuser_contact_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="booking",
            name="number_of_guests",
            field=models.IntegerField(default=0),
        ),
    ]
