# Generated by Django 4.2.7 on 2023-12-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tour_management", "0005_alter_booking_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourpackage",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tour_management.supplier",
            ),
        ),
    ]
